spring.application.name=backend
server.port=8080

# H2 Console
spring.h2.console.enabled=false
spring.h2.console.path=/h2-console

# Database Config (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/pokemontcg
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA / Hibernate (PostgreSQL)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true